require 'huginn_agent'

HuginnAgent.load 'huginn_nlp_agents/concerns/nif_api_agent_concern'
HuginnAgent.load 'huginn_nlp_agents/concerns/freme_filterable'
HuginnAgent.register 'huginn_nlp_agents/dkt_document_classification_agent'
HuginnAgent.register 'huginn_nlp_agents/dkt_ner_agent'
HuginnAgent.register 'huginn_nlp_agents/dkt_pos_agent'
HuginnAgent.register 'huginn_nlp_agents/dkt_topic_modelling_agent'
HuginnAgent.register 'huginn_nlp_agents/freme_explore_agent'
HuginnAgent.register 'huginn_nlp_agents/freme_filter_agent'
HuginnAgent.register 'huginn_nlp_agents/freme_link_agent'
HuginnAgent.register 'huginn_nlp_agents/freme_ner_agent'
HuginnAgent.register 'huginn_nlp_agents/freme_nif_converter_agent'
HuginnAgent.register 'huginn_nlp_agents/freme_pipeline_agent'
HuginnAgent.register 'huginn_nlp_agents/freme_spotlight_agent'
HuginnAgent.register 'huginn_nlp_agents/freme_terminology_agent'
HuginnAgent.register 'huginn_nlp_agents/freme_translation_agent'
